version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for HTML file."

  pre_build:
    commands:
      - echo "No pre-build steps required."

  build:
    commands:
      - echo "No build steps required."

artifacts:
  files:
    - '**/*.html' 